project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [source, issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/dbikard/dgrec
        aria-label: "Source code on GitHub"
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]