# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dgrec',
                'doc_host': 'https://dbikard.github.io',
                'git_url': 'https://github.com/dbikard/DGRec',
                'lib_path': 'dgrec'},
  'syms': { 'dgrec.core': { 'dgrec.core.align2mut': ('core.html#align2mut', 'dgrec/core.py'),
                            'dgrec.core.correct_UMI_genotypes': ('core.html#correct_umi_genotypes', 'dgrec/core.py'),
                            'dgrec.core.dgrec_genotypes': ('core.html#dgrec_genotypes', 'dgrec/core.py'),
                            'dgrec.core.genotype_UMI_counter': ('core.html#genotype_umi_counter', 'dgrec/core.py'),
                            'dgrec.core.get_UMI_genotype': ('core.html#get_umi_genotype', 'dgrec/core.py'),
                            'dgrec.core.get_genotypes': ('core.html#get_genotypes', 'dgrec/core.py'),
                            'dgrec.core.get_mutations': ('core.html#get_mutations', 'dgrec/core.py'),
                            'dgrec.core.mut_rix': ('core.html#mut_rix', 'dgrec/core.py'),
                            'dgrec.core.mut_to_str': ('core.html#mut_to_str', 'dgrec/core.py')},
            'dgrec.plotting': {'dgrec.plotting.plot_mutations': ('plotting.html#plot_mutations', 'dgrec/plotting.py')},
            'dgrec.utils': {'dgrec.utils.downsample_fastq_gz': ('utils.html#downsample_fastq_gz', 'dgrec/utils.py')}}}
