# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/DGRec',
                'doc_host': 'https://dbikard.github.io',
                'git_url': 'https://github.com/dbikard/DGRec',
                'lib_path': 'DGRec'},
  'syms': {'DGRec.core': {'DGRec.core.foo': ('core.html#foo', 'DGRec/core.py')}}}
