"""Functions to estimate the total library size (number of unique genotypes) from sampling data. Fits a hybrid power-law distribution model to genotype frequency data and extrapolates to estimate unobserved genotypes.

Docs: https://dbikard.github.io/dgrec/API/library_size.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/10_library_size.ipynb.

# %% auto #0
__all__ = ['find_best_breakpoint', 'estimate_library_size', 'estimate_library_size_constrained', 'find_best_breakpoint_mle',
           'estimate_library_size_mle', 'plot_distribution', 'estimate_library_size_lstm']

# %% ../nbs/API/10_library_size.ipynb #32f2f76e
from .utils import parse_genotypes, str_to_mut
import os
import warnings
import numpy as np
from Bio import SeqIO
import matplotlib.pyplot as plt
from scipy import stats
from typing import Dict, Any, List, Callable
from scipy.stats import linregress
from scipy.integrate import quad

# %% ../nbs/API/10_library_size.ipynb #dc574984
def _expected_distinct(counts, n_total_umis, B, alpha, G, N):
    """Expected number of distinct genotypes among `N` draws from the hybrid model.

    The head keeps its empirical probabilities; the remaining mass is spread over ranks
    B+1..G as C*j**-alpha. Shared by `estimate_library_size`, which takes alpha from the
    rank regression, and `estimate_library_size_constrained`, which solves for it.

    Returns (E_head, E_tail, C).
    """
    # 3. Define the probability distribution p_j
    # HEAD: Use empirical probabilities
    p_head = counts[:B] / n_total_umis
    p_head_mass = np.sum(p_head)

    # TAIL: Distribute remaining probability mass according to the power law
    p_tail_mass = 1.0 - p_head_mass
    
    # Calculate normalization constant C for the tail
    tail_ranks_start = B + 1
    
    # For performance, use integral approximation if G is very large
    if G > 10_000_000 and alpha != 1.0:
        power_law_sum = (G**(1.0 - alpha) - tail_ranks_start**(1.0 - alpha)) / (1.0 - alpha)
    else:
        tail_ranks = np.arange(tail_ranks_start, G + 1, dtype=np.float64)
        power_law_sum = np.sum(tail_ranks**(-alpha))

    C = p_tail_mass / power_law_sum if power_law_sum > 0 else 0

    # 4. Calculate the Final Expectation E[K_N]
    # Contribution from the head (vectorized)
    E_head = np.sum(1.0 - (1.0 - p_head)**N)

    # Contribution from the tail
    # This can be very slow for large G. We use a hybrid calculation:
    # - Exact sum for the first part of the tail.
    # - Approximation for the far tail where p_j is very small.
    E_tail = 0.0
    tail_approx_threshold = min(G, tail_ranks_start + 200_000)
    
    # Exact calculation for the first part of the tail
    ranks_for_exact_calc = np.arange(tail_ranks_start, tail_approx_threshold + 1, dtype=np.float64)
    p_tail_exact = C * (ranks_for_exact_calc**(-alpha))
    E_tail += np.sum(1.0 - (1.0 - p_tail_exact)**N)
    
    # Approximation for the rest of the tail
    # For small p, (1-p)^N ≈ 1 - N*p, so 1-(1-p)^N ≈ N*p.
    # E_tail_far ≈ Sum(N*p_j) = N * C * Sum(j^-alpha)
    if G > tail_approx_threshold:
        far_tail_start = tail_approx_threshold + 1
        # Use integral approximation for the sum
        if alpha != 1.0:
            remaining_power_law_sum = (G**(1.0 - alpha) - far_tail_start**(1.0 - alpha)) / (1.0 - alpha)
        else: # Handle alpha = 1 case
            remaining_power_law_sum = np.log(G) - np.log(far_tail_start)
        # Each genotype contributes 1-(1-p)^N, which is at most 1, so the N*p approximation
        # must not be allowed to claim more distinct genotypes than the far tail contains.
        n_far_tail = G - far_tail_start + 1
        E_tail += min(N * C * remaining_power_law_sum, float(n_far_tail))

    return E_head, E_tail, C

# %% ../nbs/API/10_library_size.ipynb #b26be281
def find_best_breakpoint(counts: np.ndarray) -> tuple[int, float, float]:
    """
    Finds the optimal breakpoint B for a hybrid power-law distribution.

    This function iterates through possible breakpoints and performs a linear
    regression on the log-log plot of the tail of the distribution (rank vs. probability).
    The optimal breakpoint is chosen as the one that maximizes the R-squared
    value of the linear fit, indicating the point where the power-law
    behavior is most pronounced.

    Args:
        counts (np.ndarray): An array of UMI counts for each observed genotype,
                             sorted in descending order.

    Returns:
        tuple[int, float, float]: A tuple containing:
            - best_b (int): The estimated optimal breakpoint B.
            - best_alpha (float): The estimated power-law exponent alpha for the tail.
            - best_intercept (float): The intercept from the log-log linear regression.
    """
    n_total = np.sum(counts)
    m_observed = len(counts)
    if m_observed < 20:
        warnings.warn("Low number of observed genotypes (< 20); cannot estimate a breakpoint.",
                      stacklevel=2)
        return None, None, None

    best_b = -1
    best_alpha = 0.0
    best_intercept = 0.0
    max_r_squared = -1.0

    # Define a search range for B: from rank 2 up to 50% of the observed genotypes,
    # which leaves enough points in the tail for a stable fit.
    b_min = 2
    b_max = int(m_observed * 0.5)

    for b_candidate in range(b_min, b_max):
        # Isolate the tail data
        tail_counts = counts[b_candidate:]
        
        tail_ranks = np.arange(b_candidate + 1, m_observed + 1)
        tail_probs = tail_counts / n_total

        # To avoid log(0), though this is unlikely with real counts
        if np.any(tail_probs <= 0):
            continue

        # Perform linear regression on the log-transformed data
        log_ranks = np.log(tail_ranks)
        log_probs = np.log(tail_probs)

        # Using scipy's linear regression function
        lin_reg_result = stats.linregress(log_ranks, log_probs)
        
        r_squared = lin_reg_result.rvalue**2
        
        # We want the B that gives the best linear fit (highest R^2) for the tail
        if r_squared > max_r_squared:
            max_r_squared = r_squared
            best_b = b_candidate
            best_alpha = -lin_reg_result.slope  # alpha is the negative of the slope
            best_intercept = lin_reg_result.intercept

    if best_b == -1:
        warnings.warn("Could not determine a stable breakpoint.", stacklevel=2)
        return None, None, None

    return best_b, best_alpha, best_intercept


def estimate_library_size(
    observed_counts: list[int],
    G: int, # total number of possible unique genotypes
    N: int, # number of cells
    verbose: bool = False,
) -> dict:
    """
    Estimates the expected number of unique genotypes sampled (K_N).

    This function uses a hybrid model:
    1. The "head" (high-frequency genotypes) uses empirical probabilities.
    2. The "tail" (low-frequency and unobserved genotypes) is modeled with a
       power-law (Zipf) distribution.

    Args:
        observed_counts (list[int]): A list of UMI counts for each observed unique genotype.
        G (int): The total number of possible unique genotypes.
        N (int): The number of cells in the culture to sample from.

    Returns:
        dict: A dictionary containing the results:
              'library_size' (int): The final estimated E[K_N].
              'B' (int): The estimated breakpoint.
              'alpha' (float): The estimated power-law exponent.
              'E_head' (float): The contribution to E[K_N] from the head.
              'E_tail' (float): The contribution to E[K_N] from the tail.
    """
    # 1. Data Preparation
    counts = np.sort(np.array(observed_counts, dtype=np.float64))[::-1]
    counts = np.trim_zeros(counts)  # Remove any zero counts if present
    n_total_umis = np.sum(counts)
    m_observed = len(counts)

    if G < m_observed:
        raise ValueError("G (total genotypes) must be greater than or equal to the number of observed genotypes.")

    # 2. Find the optimal breakpoint B, power-law exponent alpha, and intercept
    B, alpha, intercept = find_best_breakpoint(counts)
    if B is None:
        return {
        'library_size': None,
        'B': None,
        'alpha': None,
        'C': None, 
        'intercept': None, # Pass intercept for plotting
        'E_head': None,
        'E_tail': None
        }
    
    if verbose:
        print(f"Found optimal breakpoint B = {B} with tail exponent alpha = {alpha:.4f}")

    E_head, E_tail, C = _expected_distinct(counts, n_total_umis, B, alpha, G, N)

    E_KN = E_head + E_tail
    
    if verbose:
        print(f"Head probability mass (first {B} genotypes): {np.sum(counts[:B])/n_total_umis:.2f}")
        print(f"Estimated library size E[K_N]: {int(E_KN)} unique genotypes from N={N} cells.")
    
    return {
        'library_size': int(E_KN),
        'B': B,
        'alpha': alpha,
        'C': C, 
        'intercept': intercept, # Pass intercept for plotting
        'E_head': E_head,
        'E_tail': E_tail
    }

# %% ../nbs/API/10_library_size.ipynb #a96f9048
def estimate_library_size_constrained(
    observed_counts: list[int],
    G: int,                  # total number of possible unique genotypes
    N: int,                  # number of molecules to extrapolate to
    verbose: bool = False,
) -> dict:
    """Like `estimate_library_size`, but with the exponent pinned by the observed richness.

    `estimate_library_size` picks alpha to make the log-log tail of the rank-abundance curve
    as straight as possible. Nothing in that procedure requires the fitted distribution to
    imply the number of distinct genotypes that were actually seen, and on real data it
    need not: asked how many distinct genotypes `n` draws should give, where `n` is the
    depth the sample was sequenced at, it can return several times the number observed.

    This function keeps everything else - the breakpoint, the empirical head, the
    normalisation - and solves for the alpha that makes the model reproduce the observed
    count at the observed depth, then extrapolates with it. The constraint uses only the
    data, so this remains an empirical estimate; it adds a self-consistency requirement
    rather than a model of how the genotypes arise.

    It is a one-point match: it forces agreement where the sample was taken, not that the
    shape of the tail is right beyond it.

    Returns the same keys as `estimate_library_size`, plus `alpha_unconstrained`, the value
    the rank regression gives, and `observed_distinct`.
    """
    counts = np.sort(np.array(observed_counts, dtype=np.float64))[::-1]
    counts = np.trim_zeros(counts)
    n_total_umis = np.sum(counts)
    m_observed = len(counts)
    if G < m_observed:
        raise ValueError("G (total genotypes) must be greater than or equal to the number of observed genotypes.")

    B, alpha_fit, intercept = find_best_breakpoint(counts)
    if B is None:
        return {'library_size': None, 'B': None, 'alpha': None, 'alpha_unconstrained': None,
                'C': None, 'intercept': None, 'E_head': None, 'E_tail': None,
                'observed_distinct': m_observed}

    def distinct_at_observed_depth(alpha):
        e_head, e_tail, _ = _expected_distinct(counts, n_total_umis, B, alpha, G, n_total_umis)
        return e_head + e_tail

    # U is decreasing in alpha: a steeper tail concentrates the mass on fewer genotypes
    lo, hi = 0.5, 6.0
    if distinct_at_observed_depth(lo) < m_observed or distinct_at_observed_depth(hi) > m_observed:
        warnings.warn("No exponent in [0.5, 6] reproduces the observed number of genotypes.",
                      stacklevel=2)
        return {'library_size': None, 'B': B, 'alpha': None, 'alpha_unconstrained': alpha_fit,
                'C': None, 'intercept': intercept, 'E_head': None, 'E_tail': None,
                'observed_distinct': m_observed}
    for _ in range(80):
        mid = (lo + hi) / 2
        if distinct_at_observed_depth(mid) > m_observed: lo = mid
        else: hi = mid
    alpha = (lo + hi) / 2

    if verbose:
        print(f"rank regression gives alpha = {alpha_fit:.4f}, which implies "
              f"{distinct_at_observed_depth(alpha_fit):,.0f} genotypes at the observed depth "
              f"against {m_observed:,} seen; constrained alpha = {alpha:.4f}")

    E_head, E_tail, C = _expected_distinct(counts, n_total_umis, B, alpha, G, N)
    return {
        'library_size': int(E_head + E_tail),
        'B': B,
        'alpha': alpha,
        'alpha_unconstrained': alpha_fit,
        'C': C,
        'intercept': intercept,
        'E_head': E_head,
        'E_tail': E_tail,
        'observed_distinct': m_observed,
    }

# %% ../nbs/API/10_library_size.ipynb #868960ac
def _zeta_sums(alpha, start, G, cut=200_000):
    """sum_{j=start}^{G} j**-alpha and sum_{j=start}^{G} j**-alpha * ln j.

    Exact over the first `cut` ranks, integral approximation beyond, matching how
    `_expected_distinct` handles the same sum.
    """
    hi = min(G, start + cut)
    j = np.arange(start, hi + 1, dtype=np.float64)
    s = np.sum(j**-alpha)
    sl = np.sum(j**-alpha * np.log(j))
    if G > hi:
        a, b, e = hi + 1.0, float(G), 1.0 - alpha
        s += (b**e - a**e) / e
        F = lambda x: x**e * (np.log(x) / e - 1.0 / e**2)   # integral of x**-alpha * ln x
        sl += F(b) - F(a)
    return s, sl


def _fit_alpha_mle(counts, B, G):
    """Maximum-likelihood exponent for p_j proportional to j**-alpha over the tail ranks.

    Each molecule that fell outside the head landed on a tail genotype of known rank, so
    the log-likelihood is sum_j c_j * log(C * j**-alpha). Differentiating, the maximum is
    where the model's mean log-rank per tail molecule equals the observed one, which is a
    single monotone equation in alpha.
    """
    ranks = np.arange(B + 1, len(counts) + 1, dtype=np.float64)
    tail = counts[B:]
    observed_mean_log_rank = np.sum(tail * np.log(ranks)) / np.sum(tail)
    lo, hi = 0.05, 6.0
    for _ in range(60):
        mid = (lo + hi) / 2
        s, sl = _zeta_sums(mid, B + 1, G)
        if sl / s > observed_mean_log_rank: lo = mid   # model too spread out, steepen
        else: hi = mid
    return (lo + hi) / 2


def _ks_distance(counts, B, alpha):
    """Kolmogorov-Smirnov distance between the observed and fitted distribution of
    probability mass across the observed tail ranks."""
    ranks = np.arange(B + 1, len(counts) + 1, dtype=np.float64)
    tail = counts[B:]
    empirical = np.cumsum(tail) / np.sum(tail)
    model = ranks**-alpha
    model = np.cumsum(model) / np.sum(model)
    return float(np.max(np.abs(empirical - model)))


def find_best_breakpoint_mle(counts: np.ndarray, G: int) -> tuple[int, float, float]:
    """Breakpoint and exponent by maximum likelihood and Kolmogorov-Smirnov distance.

    The alternative to `find_best_breakpoint`, which fits the exponent by least squares on
    the log-log rank plot and picks the breakpoint maximising R squared. Neither of those
    is a good criterion: least squares on log-log is a biased estimator of a power-law
    exponent, and R squared says nothing about whether a power law describes the data. Here
    the exponent is fitted by maximum likelihood and the breakpoint chosen to minimise the
    KS distance between the observed and fitted distributions.

    Candidate breakpoints are taken on a log-spaced grid up to half the observed genotypes,
    which is ample: the breakpoint that wins is small.

    Returns (B, alpha, ks_distance).
    """
    m_observed = len(counts)
    if m_observed < 20:
        warnings.warn("Low number of observed genotypes (< 20); cannot estimate a breakpoint.",
                      stacklevel=2)
        return None, None, None
    candidates = sorted({int(round(b)) for b in
                         np.geomspace(2, max(3, int(m_observed * 0.5)), num=40)})
    best = (np.inf, None, None)
    for B in candidates:
        if B >= m_observed - 2: continue
        alpha = _fit_alpha_mle(counts, B, G)
        D = _ks_distance(counts, B, alpha)
        if D < best[0]: best = (D, B, alpha)
    D, B, alpha = best
    return B, alpha, D


def estimate_library_size_mle(
    observed_counts: list[int],
    G: int,                  # total number of possible unique genotypes
    N: int,                  # number of molecules to extrapolate to
    verbose: bool = False,
) -> dict:
    """Like `estimate_library_size`, but fitting the tail by maximum likelihood.

    Same model, same head, same normalisation; only the way the exponent and breakpoint are
    chosen differs. See `find_best_breakpoint_mle`.

    On the bundled example this moves the exponent from about 0.75 to about 1.3 and brings
    the number of genotypes the model expects at the sequenced depth to within a fifth of
    the number actually seen, where the least-squares fit expects nearly three times as
    many. Nothing here asks it to match: the agreement is a consequence of the estimator.

    Returns the same keys as `estimate_library_size`, plus `ks_distance`.
    """
    counts = np.sort(np.array(observed_counts, dtype=np.float64))[::-1]
    counts = np.trim_zeros(counts)
    n_total_umis = np.sum(counts)
    m_observed = len(counts)
    if G < m_observed:
        raise ValueError("G (total genotypes) must be greater than or equal to the number of observed genotypes.")

    B, alpha, D = find_best_breakpoint_mle(counts, G)
    if B is None:
        return {'library_size': None, 'B': None, 'alpha': None, 'C': None,
                'intercept': None, 'E_head': None, 'E_tail': None, 'ks_distance': None}

    if verbose:
        print(f"MLE fit: B = {B}, alpha = {alpha:.4f}, KS distance = {D:.4f}")

    E_head, E_tail, C = _expected_distinct(counts, n_total_umis, B, alpha, G, N)
    return {
        'library_size': int(E_head + E_tail),
        'B': B,
        'alpha': alpha,
        'C': C,
        'intercept': None,
        'E_head': E_head,
        'E_tail': E_tail,
        'ks_distance': D,
    }

# %% ../nbs/API/10_library_size.ipynb #62463604
def plot_distribution(counts: np.ndarray, results: dict):
    """
    Plots the probability distribution on a log-log scale.

    Args:
        counts (np.ndarray): Sorted array of observed genotype counts.
        results (dict): The dictionary returned by estimate_expected_genotypes.
    """
    counts = np.sort(np.array(counts, dtype=np.float64))[::-1]
    counts = np.trim_zeros(counts)
    n_total_umis = np.sum(counts)
    m_observed = len(counts)
    ranks = np.arange(1, m_observed + 1)
    probs = counts / n_total_umis

    B = results['B']
    alpha = results['alpha']
    intercept = results['intercept'] # Get the intercept from the regression

    plt.figure(figsize=(8, 4))

    # Plot all empirical data points
    plt.scatter(ranks, probs, s=15, alpha=0.7, edgecolors='k', facecolors='none', label='Empirical Probabilities')

    # Highlight the head and tail
    plt.scatter(ranks[:B], probs[:B], s=20, c='blue', label='Head')
    plt.scatter(ranks[B:], probs[B:], s=20, c='orange', label='Tail')

    # Plot the power-law fit for the tail using the regression intercept for visualization
    # log(p) = -alpha * log(j) + intercept  =>  p = exp(intercept) * j^(-alpha)
    tail_ranks_fit = np.arange(B + 1, m_observed + 1)
    power_law_fit = np.exp(intercept) * (tail_ranks_fit**(-alpha))
    plt.plot(tail_ranks_fit, power_law_fit, color='red', linestyle='-', linewidth=2, label=f'Power-law Fit (α={alpha:.2f})')

    # Draw the breakpoint line
    plt.axvline(x=B, color='gray', linestyle='--', label=f'Breakpoint B = {B}')

    plt.xscale('log')
    plt.yscale('log')
    plt.xlabel('Rank (log scale)')
    plt.ylabel('Probability p_j (log scale)')
    plt.title('Genotype Probability Distribution with Power-Law Fit')
    plt.legend()
    plt.grid(True, which="both", ls="--", linewidth=0.5)
    plt.tight_layout()
    plt.show()

# %% ../nbs/API/10_library_size.ipynb #61eb1734
def estimate_library_size_lstm(
    TR: str,                  # the template region the library was built from
    n: int,                   # number of mutagenized molecules to extrapolate to
    n_samples: int = 10000,   # Monte Carlo sample drawn from the model
    batch_size: int = 4000,   # scoring batch size
    seed: int = None,         # seed for reproducibility
) -> dict:
    """Expected number of distinct genotypes among `n` mutagenized molecules, from the LSTM.

    `estimate_library_size` answers the same question from the observed counts alone, by
    fitting a power law to the tail of the rank-abundance curve and extrapolating it. It
    needs that assumed shape because the empirical estimate of a genotype's probability is
    zero for every genotype that was never observed.

    The LSTM does not need a stand-in: it assigns a probability to any VR, observed or not.
    So the exact expression

        U(n) = sum_j ( 1 - (1 - p_j)^n )

    can be estimated with no assumption about the shape of the distribution, by sampling
    genotypes from the model and reweighting each by its own probability,

        U(n) = E_{j ~ p} [ ( 1 - (1 - p_j)^n ) / p_j ],

    which needs only the ability to sample and to score. Note that this never looks at the
    observed counts: it takes a TR, not a dataset, and so reports what the reverse
    transcriptase would produce under the error profile the model was trained on. An
    experiment shaped by anything else - selection on the product, a bottleneck, a different
    DGR system - will not be reflected here.

    `n` counts **mutagenized molecules, not cells**: the model describes the mutational
    profile given that conversion happened, not the rate of conversion.

    Requires the `lstm` extra.
    """
    #imported here, not at module level: dgrec/__init__.py imports this module, and
    #dgrec.lstm pulls in TensorFlow, which is an optional extra
    from dgrec.lstm import (generate_sequences_oneTR, _teacher_forced_loglik,
                            _require_tensorflow)
    _require_tensorflow()
    if seed is not None: np.random.seed(seed)

    vrs = generate_sequences_oneTR(TR, n_samples)
    logp = np.concatenate([
        _teacher_forced_loglik([TR] * len(vrs[i:i+batch_size]), vrs[i:i+batch_size])
        for i in range(0, len(vrs), batch_size)
    ])
    p = np.exp(logp)

    # (1-(1-p)^n)/p, computed so that it stays accurate for very small p
    weights = -np.expm1(n * np.log1p(-p)) / p
    return {
        'library_size': float(weights.mean()),
        'se': float(weights.std(ddof=1) / np.sqrt(len(weights))),
        'n': int(n),
        'n_samples': int(n_samples),
        'simpson_effective': float(1.0 / p.mean()),
        'shannon_effective': float(np.exp((-logp).mean())),
    }
