"""Deep learning models to predict the population of VR (Variable Region) sequences generated by a given TR design. Uses LSTM neural networks trained on DGRec experimental data to model bRT's position-dependent, context-dependent error-prone reverse transcription, including the snowball effect where prior mutations increase subsequent error rates."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/09_lstm.ipynb.

# %% auto #0
__all__ = ['EPS', 'one_hot_encode', 'one_hot_decode', 'separate_model', 'generate_sequence_from_onehot', 'sequences_same_length',
           'pad_sequence', 'to_tensor_inputs', 'generate_sequences', 'generate_sequences_oneTR', 'EvaluateTR_to_prot',
           'optimize_sequence_display_proteins', 'compute_likelihood', 'compute_likelihood_batch',
           'compute_likelihood_list', 'compute_likelihood_matrix']

# %% ../nbs/API/09_lstm.ipynb #f6f95cf2-5340-4818-8b9e-246fea3f7879
import logomaker
import numpy as np
from tqdm import tqdm
from .example_data import get_example_data_dir
import os
import matplotlib.pyplot as plt
from collections import Counter,defaultdict
from itertools import product
from .utils import (codon_usage_ecoli, genetic_code, CODON_TO_AA,
                          AA, AA_IDS, AA_TO_CODONS, nt_to_codons,
                          codons_to_aa, nt_prot)

try:
    import tensorflow as tf
    from tensorflow.keras.utils import to_categorical
    from tensorflow.keras import layers, models
    from tensorflow.keras.models import load_model
    import tensorflow.keras.backend as K
    from tensorflow.keras.utils import register_keras_serializable
    _TF_AVAILABLE = True
except ImportError:
    _TF_AVAILABLE = False

EPS = 1e-8

# %% ../nbs/API/09_lstm.ipynb #zwq1hs8fd0r
def _require_tensorflow():
    """Raise an informative error if TensorFlow is not installed."""
    if not _TF_AVAILABLE:
        raise ImportError(
            "TensorFlow is required for LSTM-based sequence generation. "
            "Install it with: pip install dgrec[lstm]"
        )

# %% ../nbs/API/09_lstm.ipynb #0af10dfc-65cc-4e39-a9a7-56a9b72ad7fa
if _TF_AVAILABLE:
    # --- Custom loss and metrics ---
    @tf.keras.utils.register_keras_serializable(package="custom_losses")
    def masked_categorical_crossentropy(y_true, y_pred, mask=None):
        per_timestep_loss = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
        if mask is not None:
            if len(mask.shape) == 3:
                mask = tf.reduce_max(mask, axis=-1)
            per_timestep_loss *= mask
            loss = tf.reduce_sum(per_timestep_loss) / (tf.reduce_sum(mask) + EPS)
        else:
            mask = tf.cast(tf.reduce_max(tf.abs(y_true), axis=-1) > 0, tf.float32)
            per_timestep_loss *= mask
            loss = tf.reduce_sum(per_timestep_loss) / (tf.reduce_sum(mask) + EPS)
        return loss
    
    @tf.keras.utils.register_keras_serializable(package="custom_metrics")
    def masked_accuracy(y_true, y_pred, mask=None):
        mask_internal = tf.cast(tf.reduce_max(tf.abs(y_true), axis=-1) > 0, tf.float32) if mask is None else tf.cast(mask, tf.float32)
        if len(mask_internal.shape) == 3:
            mask_internal = tf.reduce_max(mask_internal, axis=-1)
        y_true_labels = tf.argmax(y_true, axis=-1)
        y_pred_labels = tf.argmax(y_pred, axis=-1)
        matches = tf.cast(tf.equal(y_true_labels, y_pred_labels), tf.float32) * mask_internal
        return tf.reduce_sum(matches) / (tf.reduce_sum(mask_internal) + EPS)
    
    @tf.keras.utils.register_keras_serializable()
    class DetachMask(layers.Layer):
        def call(self, inputs):
            return tf.identity(inputs)
        def compute_mask(self, inputs, mask=None):
            return None
else:
    def masked_categorical_crossentropy(y_true, y_pred):
        _require_tensorflow()

    def masked_accuracy(y_true, y_pred):
        _require_tensorflow()
    def DetachMask(layer):
        _require_tensorflow()

def one_hot_encode(sequence, vocab_size=4):
    """Converts a DNA sequence string to a one-hot encoded numpy array of shape (len, vocab_size)."""
    _require_tensorflow()
    mapping = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    integer_encoded = [mapping[base] for base in sequence]
    onehot_encoded = to_categorical(integer_encoded, num_classes=vocab_size)
    return onehot_encoded

def one_hot_decode(encoded_sequence):
    """Converts a one-hot encoded array back to a DNA sequence string."""
    # Reverse the mapping used in encoding
    reverse_mapping = {0: 'A', 1: 'C', 2: 'G', 3: 'T'}
    
    # Get the index of the max value in each one-hot vector (which corresponds to the base index)
    integer_decoded = np.argmax(encoded_sequence, axis=1)
    
    # Convert the integer sequence back to the DNA bases using the reverse mapping
    decoded_sequence = ''.join([reverse_mapping[i] for i in integer_decoded])
    
    return decoded_sequence

def separate_model(model):
    """
    Disentangle the two-stage masked LSTM model into two parts:
      1. First BiLSTM + TimeDistributed Dense layers
      2. Second LSTM + Final Dense (with initial states for generation)
    """
    _require_tensorflow()
    lstm_units = 16
    vocab_size = 4  # A, C, G, T

    # --- Part 1: First BiLSTM + Dense(s) ---
    inputs = layers.Input(shape=(None, vocab_size+1), name="DNA_input_sep")

    masked_seq = layers.Masking(mask_value=0.0)(inputs)
    bilstm_out = layers.Bidirectional(
        layers.LSTM(lstm_units//2, return_sequences=True),
        name="bilstm_1_sep"
    )(masked_seq)

    inter_dense_out = layers.TimeDistributed(
        layers.Dense(vocab_size+2, activation="softmax"),
        name="inter_dense_sep"
    )(bilstm_out)

    inter_dense_relu_out = layers.TimeDistributed(
        layers.Dense(2, activation="relu"),
        name="inter_dense_relu_sep"
    )(bilstm_out)

    # First part outputs both intermediate representations
    first_part_model = models.Model(
        inputs=inputs,
        outputs=[inter_dense_out, inter_dense_relu_out]
    )

    # Transfer weights by name
    first_part_model.get_layer("bilstm_1_sep").set_weights(
        model.get_layer("bilstm_1").get_weights()
    )
    first_part_model.get_layer("inter_dense_sep").set_weights(
        model.get_layer("intermediate_dense").get_weights()
    )
    first_part_model.get_layer("inter_dense_relu_sep").set_weights(
        model.get_layer("intermediate_dense_relu").get_weights()
    )

    # --- Part 2: Second LSTM + Final Dense ---
    inputs_seq = layers.Input(shape=(None, vocab_size+1), name="DNA_input2_sep")
    inputs_mut = layers.Input(shape=(None, 2 * vocab_size + 1), name="mutation_input2_sep")
    inter_out = layers.Input(shape=(None, vocab_size+2), name="inter_dense_out_sep")
    inter_relu_out = layers.Input(shape=(None, 2), name="inter_dense_relu_out_sep")
    initial_h = layers.Input(shape=(lstm_units,), name="init_h")
    initial_c = layers.Input(shape=(lstm_units,), name="init_c")

    concat_inputs = layers.Concatenate(name="concat_sep")(
        [inputs_seq, inputs_mut, inter_out, inter_relu_out]
    )
    masked_concat = layers.Masking(mask_value=0.0)(concat_inputs)

    lstm_out, state_h, state_c = layers.LSTM(
        lstm_units, return_sequences=True, return_state=True, name="lstm_2_sep"
    )(masked_concat, initial_state=[initial_h, initial_c])

    final_out = layers.TimeDistributed(
        layers.Dense(vocab_size, activation="softmax"),
        name="final_dense_sep"
    )(lstm_out)

    second_part_model = models.Model(
        inputs=[inputs_seq, inputs_mut, inter_out, inter_relu_out, initial_h, initial_c],
        outputs=[final_out, state_h, state_c]
    )

    # Transfer weights
    second_part_model.get_layer("lstm_2_sep").set_weights(
        model.get_layer("lstm_2").get_weights()
    )
    second_part_model.get_layer("final_dense_sep").set_weights(
        model.get_layer("final_dense").get_weights()
    )

    return first_part_model, second_part_model

_models_cache = {}

def _get_models():
    """Load LSTM models on first use."""
    _require_tensorflow()
    if 'firstmodel' not in _models_cache:
        data_path = get_example_data_dir()
        model_name = 'LSTM_model_8_16.keras'
        model_path = os.path.join(data_path, model_name)
        # --- Load your full trained model first ---
        model_TR_to_VR = tf.keras.models.load_model(
            model_path, #"LSTM_model_8_16_tf220.keras"
            custom_objects={
                'masked_categorical_crossentropy': masked_categorical_crossentropy,
                'masked_accuracy': masked_accuracy,
                'DetachMask': DetachMask  # placeholder for custom DetachMask
            }
        )
        _models_cache['firstmodel'], _models_cache['secondmodel'] = separate_model(model_TR_to_VR)
    return _models_cache['firstmodel'], _models_cache['secondmodel']

def generate_sequence_from_onehot(X, firstmodel=None, secondmodel=None):
    """
    Generate a sequence using separated masked LSTM models.
    
    X: one-hot encoded sequence (batch, time, vocab_size+2)  # input_seq
    firstmodel: first part model (BiLSTM -> [softmax dense, ReLU dense])
    secondmodel: second part model (Concat -> LSTM -> final dense)
    """
    if firstmodel is None or secondmodel is None:
        firstmodel, secondmodel = _get_models()
    size, seq_length, input_dim = X.shape
    vocab_size = 4   # A, C, G, T
    lstm_units = 16

    # Initial states for second LSTM
    initial_h = np.zeros((size, lstm_units))
    initial_c = np.zeros((size, lstm_units))

    # First part (BiLSTM + two dense layers)
    inter_softmax_out, inter_relu_out = firstmodel.predict(X)

    # Mutation input (start token)
    X_mut = np.zeros((size, 1, vocab_size * 2 + 1))
    X_mut[:, 0, -1] = 1  # mark start

    generated_sequence = np.zeros((size, seq_length, vocab_size))

    for t in tqdm(range(seq_length), desc="Generating sequence"):
        output, new_h, new_c = secondmodel.predict([
            X[:, t:t+1, :],                       # input_seq at step t
            X_mut,                                # mutation input
            inter_softmax_out[:, t:t+1, :],       # intermediate softmax output
            inter_relu_out[:, t:t+1, :],          # intermediate relu output
            initial_h, initial_c                  # LSTM states
        ],verbose=0)

        # Sample next nucleotide
        probs = output[:, 0, :]  # (batch, vocab_size)
        next_word_idx = [np.random.choice(vocab_size, p=p) for p in probs]
        next_word_one_hot = np.zeros((size, vocab_size))
        next_word_one_hot[np.arange(size), next_word_idx] = 1

        generated_sequence[:, t, :] = next_word_one_hot

        # Update states
        initial_h, initial_c = new_h, new_c

        # Update mutation input for next step
        if t < seq_length - 1:
            X_mut[:, 0, :vocab_size] = X[:, t, :vocab_size]        # original nucleotide
            X_mut[:, 0, vocab_size:2*vocab_size] = next_word_one_hot  # predicted nucleotide
            X_mut[:, 0, -1] = 0  # remove start flag after t=0

    return generated_sequence


def sequences_same_length(sequences):
    """
    Check if all sequences in a list have the same length.
    
    Parameters:
    - sequences: list of sequences (e.g., strings, lists, or arrays)
    
    Returns:
    - bool: True if all sequences have the same length, False otherwise.
    """
    # Get the length of the first sequence
    first_length = len(sequences[0])

    # Check if all sequences have the same length
    for seq in sequences:
        if len(seq) != first_length:
            return False

    return True


def pad_sequence(seq, maxlen, padding_value=0):
    """Right-pads a 2D array to the specified length with padding_value."""
    pad_width = ((0, maxlen - seq.shape[0]), (0, 0))  # pad rows only
    return np.pad(seq, pad_width, mode='constant', constant_values=padding_value)

def to_tensor_inputs(*args):
    """Converts numpy arrays to TensorFlow tensors."""
    _require_tensorflow()
    return [tf.convert_to_tensor(x) for x in args]

# %% ../nbs/API/09_lstm.ipynb #8a80d927-30cc-4946-bfc5-3fb934471726
def generate_sequences(X_seq: list[str] #list of TR sequences
                      ) -> list[str]:
    """
    Generate VR sequences from a list of TR sequences.

    Each TR sequence produces exactly one VR sequence.

    Parameters
    ----------
    X_seq : list of str
        List of TR nucleotide sequences (e.g. "ATCG").
        For faster generation, all sequences should have the same length.

    Returns
    -------
    list of str
        List of generated VR sequences, in the same order as `X_seq`.

    Notes
    -----
    - If all input sequences have the same length, generation is vectorized
      for improved performance.
    - Output sequences are returned in the original (non-reversed) order.
    """
    X = [
        np.concatenate(
            (
                one_hot_encode(seq[::-1]),
                [[i] for i in range(len(seq))]
            ),
            axis=1
        )
        for seq in X_seq
    ]

    if sequences_same_length(X_seq):
        Y = generate_sequence_from_onehot(np.array(X))
        return [one_hot_decode(y)[::-1] for y in Y]

    max_len = max(len(seq) + 2 for seq in X_seq)
    lengths = np.array([len(seq) for seq in X_seq])

    X_padded = np.array([pad_sequence(seq, max_len) for seq in X])
    Y = generate_sequence_from_onehot(X_padded)

    return [
        one_hot_decode(Y[i])[:lengths[i]][::-1]
        for i in range(len(Y))
    ]

#| export
def generate_sequences_oneTR(TR: str #TR sequence
                             , n: int = 1000 #Number of VR to generate
                            ) -> list[str]:
    """
    Generate multiple VR sequences from a single TR sequence.

    Parameters
    ----------
    TR : str
        Input TR nucleotide sequence.
    n : int, default=1000
        Number of VR sequences to generate.

    Returns
    -------
    list of str
        List of `n` generated VR sequences.
    """
    return generate_sequences([TR] * n)

# %% ../nbs/API/09_lstm.ipynb #493ad454-95a7-4eff-bd9c-ae857afa003e
def EvaluateTR_to_prot(
    TR: str #The TR sequence 
    ,NDGR: int = 100 #Number of VR to generate for the protein logo
    ,offset: int = 0 #The offset for protein translation
) -> Counter:
    """
    Evaluate protein diversity accessible from a TR sequence via DGR.

    Generates VR sequences from a single TR, translates them into proteins,
    and displays a protein sequence logo based on amino-acid frequencies.

    Parameters
    ----------
    TR : str
        Input TR nucleotide sequence.
    NDGR : int, default=100
        Number of VR sequences to generate from the TR.
    offset : int, default=0
        Nucleotide offset applied before translation to protein.

    Returns
    -------
    collections.Counter
        Counts of translated protein sequences.

    Notes
    -----
    - Translation is performed after applying the nucleotide `offset`.
    - The sequence logo shows per-position amino-acid probabilities.
    """
    VR = generate_sequences_oneTR(TR, NDGR)

    proteins = [
        nt_prot(vr[offset:])
        for vr in VR
    ]

    # Build amino-acid count matrix
    df = logomaker.alignment_to_matrix(
        sequences=proteins,
        to_type="counts"
    )

    # Normalize counts to probabilities per position
    df = df.div(df.sum(axis=1), axis=0)

    plt.figure(figsize=(12, 4))
    logomaker.Logo(
        df,
        color_scheme="chemistry",
        shade_below=0.5,
        fade_below=0.5
    )
    plt.title("Protein Sequence Logo")
    plt.ylabel("Frequency")
    plt.xlabel("Amino acid position")
    plt.tight_layout()
    plt.show()

    return Counter(proteins)


# %% ../nbs/API/09_lstm.ipynb #42378de4-e643-4097-86b8-3a709638923a
from . import predictions

def optimize_sequence_display_proteins(original_seq: str,
    frame_offset: int = 0,
    dict_allowed_AAs : dict = defaultdict(list),
    CHANGES: int = 6,
    freq_min: float = 0.2,
    N: int = 1,
    forbidden_positions: list[int] = [],
    threshold: float = 0.7,
    codon_usage: dict = codon_usage_ecoli,
    NDGR: int = 100
):
    """
    Optimize a DNA sequence via synonymous codon substitutions and shows the sequence logo for each of the optimal sequences.

    This function performs a beam-search–based optimization of a nucleotide
    sequence by iteratively proposing single-codon synonymous changes and
    evaluating them with the two scoring functions. The search stops early if a
    variant meets the specified score thresholds, otherwise the best Pareto-
    optimal solution is returned.

    Parameters
    ----------
    original_seq : str
        Original DNA sequence to optimize.
    frame_offset : int, default=0
        Reading-frame offset (0, 1, or 2) used when grouping codons.
    dict_allowed_AAs : dict, defaultdict(list)
        Dictionary of positions (keys) and AAs (values) where you want to reach all AAs in the list with the codon. If not mentioned, does as before.
        Selects for codons which do not reach (by adenine mutation) stop codons. If not possible, allow them anyway.
    CHANGES : int, default=6
        Maximum number of codon substitutions allowed (on top of the AAs requirements from the previous argument).
    freq_min : float, default=0.2
        Lowest usage frequency acceptable.
    N : int, default=1
        Number of putative TR to output.
    forbidden_positions : list[int], optional
        Nucleotide positions that must not be modified.
    threshold : float, default=0.7
        Minimum required value for both `Score_TRSp` and `Score_TRSpAvd` to
        accept a sequence as optimal.
    codon_usage : dict, optional
        Codon usage table of E. Coli mapping amino acids to codons and frequencies.
    NDGR : int, default=100
        Number of sequences to generate via the LSTM for sequence logo estimation. 
    Returns
    -------
    dict
        Dictionary containing:
        - `Original_Sequence` : str  
          Input DNA sequence.
        - `New_Variant` : str  
          Optimized DNA sequence.
        - `Rank` : int or None  
          rank of the sequence (by score).
        - `Score` : float or None  
          score of the selected variant (geometrical mean).
        - `Score_TRSp` : float or None  
          TR+Sp score of the selected variant.
        - `Score_TRSpAvd` : float or None  
          Avd+TR+Sp score of the selected variant.
        - `Proteins` : Counter
          The proteins that are generated by the DGR.  
    Notes
    -----
    - The algorithm keeps only Pareto-optimal candidates at each iteration.
    - If no variant satisfies the threshold criteria, the best-scoring
      sequence after `CHANGES` iterations is returned.
    - Internal scoring and plotting are handled by `evaluate_sequences`.

    Examples
    --------
    ```python
    result = optimize_sequence("ATGGCTGCTTAA")
    result["New_Variant"]
    ```
    """
    record=predictions.optimize_sequence(
    original_seq,
    frame_offset,
    dict_allowed_AAs,
    CHANGES,
    freq_min,
    N,
    forbidden_positions,
    threshold,
    codon_usage
)
    for i in range(len(record)):
        Prot=EvaluateTR_to_prot(record[i]["New_Variant"],NDGR=NDGR,offset=frame_offset)
        record[i]['Proteins']=Prot
    return record

# %% ../nbs/API/09_lstm.ipynb #265d2712-2bfa-482d-8c19-420b904a0350
def compute_likelihood(TR, VR):
    """
    Compute the log-likelihood of generating a variant sequence (VR)
    given a template/reference sequence (TR).
    
    Parameters
    ----------
    TR : str
        Reference/template sequence.
    VR : str
        Variant sequence to score.

    Returns
    -------
    float
        Log-likelihood of VR given TR.
    """
    assert len(TR) == len(VR), "Mismatched lengths"

    firstmodel, secondmodel = _get_models()

    vocab_size = 4
    lstm_units = 16
    seq_length = len(TR)

    # Encode and reverse sequences.
    # X includes one-hot encoding of TR plus positional indices.
    X = np.array([
        np.concatenate(
            (one_hot_encode(TR[::-1]), [[i] for i in range(len(TR))]),
            axis=1
        )
    ])

    # One-hot encode reversed VR (target sequence)
    Y = np.array([one_hot_encode(VR[::-1])])

    # Run first model to obtain intermediate representations
    inter_softmax_out, inter_relu_out = firstmodel.predict(X, verbose=0)

    # Initialize mutation model input tensor
    # Shape: (batch, sequence length, 2*vocab_size + 1)
    X_mut = np.zeros((1, seq_length, 2 * vocab_size + 1))

    # Set start token for first timestep
    X_mut[:, 0, -1] = 1

    # Populate mutation input using previous TR and VR tokens
    for t in range(1, seq_length):
        X_mut[:, t, :vocab_size] = X[:, t - 1, :vocab_size]
        X_mut[:, t, vocab_size:2 * vocab_size] = Y[:, t - 1, :]

    # Initialize LSTM hidden and cell states
    initial_h = np.zeros((1, lstm_units))
    initial_c = np.zeros((1, lstm_units))

    # Run second model for full sequence prediction
    outputs, _, _ = secondmodel.predict(
        [X, X_mut, inter_softmax_out, inter_relu_out, initial_h, initial_c],
        verbose=0
    )

    # Compute total log-likelihood over sequence
    log_likelihoods = []
    for b in range(1):
        log_prob = 0.0
        for t in range(seq_length):
            prob = outputs[b, t, np.argmax(Y[b, t])]
            log_prob += np.log(prob + 1e-8)
        log_likelihoods.append(log_prob)

    return log_likelihoods[0]

# %% ../nbs/API/09_lstm.ipynb #4f2e37b5-bee4-4b0a-b053-c032307a047e
def compute_likelihood_batch(TR_batch, VR_batch):
    """
    Compute log-likelihoods for a batch of (TR, VR) sequence pairs.

    All sequences in the batch must:
    - Have matching TR/VR lengths
    - Share the same sequence length across the batch

    Parameters
    ----------
    TR_batch : list of str
        List of reference/template sequences.
    VR_batch : list of str
        List of variant sequences.

    Returns
    -------
    list of float
        Log-likelihoods for each (TR, VR) pair.
    """
    assert all(len(tr) == len(vr) for tr, vr in zip(TR_batch, VR_batch)), "Mismatched lengths"

    firstmodel, secondmodel = _get_models()

    vocab_size = 4
    lstm_units = 16
    batch_size = len(TR_batch)
    seq_length = max ([len(tr) for tr in TR_batch])

    # Encode and reverse TR sequences with positional indices
    X = np.array([
        np.concatenate(
            (one_hot_encode(TR_batch[k][::-1]), [[i] for i in range(len(TR_batch[k]))]),
            axis=1
        )
        for k in range(len(TR_batch))
    ])

    # Encode and reverse VR sequences
    Y = np.array([one_hot_encode(vr[::-1]) for vr in VR_batch])

    # First model forward pass
    inter_softmax_out, inter_relu_out = firstmodel.predict(X, verbose=0)

    # Initialize mutation input tensor
    X_mut = np.zeros((batch_size, seq_length, 2 * vocab_size + 1))

    # Start tokens at first timestep
    X_mut[:, 0, -1] = 1

    # Fill mutation inputs using previous TR and VR tokens
    for t in range(1, seq_length):
        X_mut[:, t, :vocab_size] = X[:, t - 1, :vocab_size]
        X_mut[:, t, vocab_size:2 * vocab_size] = Y[:, t - 1, :]

    # Initialize LSTM states for entire batch
    initial_h = np.zeros((batch_size, lstm_units))
    initial_c = np.zeros((batch_size, lstm_units))

    # Run second model
    outputs, _, _ = secondmodel.predict(
        [X, X_mut, inter_softmax_out, inter_relu_out, initial_h, initial_c],
        verbose=0
    )

    # Accumulate log-likelihoods per sequence
    log_likelihoods = []
    for b in range(batch_size):
        log_prob = 0.0
        for t in range(seq_length):
            prob = outputs[b, t, np.argmax(Y[b, t])]
            log_prob += np.log(prob + 1e-100)
        log_likelihoods.append(log_prob)

    return log_likelihoods

# %% ../nbs/API/09_lstm.ipynb #c2bc5a52-813b-4d64-8c3b-21b5d5e01ce9
def compute_likelihood_list(TR_list, VR_list):
    """
    Compute log-likelihoods for (TR, VR) pairs.

    Parameters
    ----------
    TR_list : list of str
        Reference/template sequences.
    VR_list : list of str
        Variant sequences.

    Returns
    -------
    list of float
        Log-likelihoods in the same order as input.
    """
    assert len(TR_list) == len(VR_list)
    assert all(len(tr) == len(vr) for tr, vr in zip(TR_list, VR_list)), \
        "Mismatched TR/VR lengths"

    # --- group indices by sequence length ---
    length_to_indices = {}
    for i, tr in enumerate(TR_list):
        L = len(tr)
        length_to_indices.setdefault(L, []).append(i)

    # output container
    log_likelihoods = [None] * len(TR_list)

    # --- process each length group ---
    for L, indices in length_to_indices.items():
        TR_batch = [TR_list[i] for i in indices]
        VR_batch = [VR_list[i] for i in indices]

        batch_lls = compute_likelihood_batch(
            TR_batch,
            VR_batch
        )

        # restore original order
        for idx, ll in zip(indices, batch_lls):
            log_likelihoods[idx] = ll

    return log_likelihoods


# %% ../nbs/API/09_lstm.ipynb #48e675a6-4402-43cf-88b3-a78bee57ac3f
def compute_likelihood_matrix(
    TR_list,
    VR_list,
    batch_size=64
):
    """
    Compute a matrix of log-likelihoods where each entry (i, j)
    corresponds to the log-likelihood of generating VR_list[j]
    from TR_list[i].

    Sequences with mismatched lengths are assigned -inf.

    Parameters
    ----------
    TR_list : list of str
        List of reference/template sequences.
    VR_list : list of str
        List of variant sequences.
    batch_size : int
        (Currently unused) Intended batch size for future optimization.

    Returns
    -------
    list of list of float
        Log-likelihood matrix of shape (len(TR_list), len(VR_list)).
    """
    result_matrix = []

    for i in range(len(TR_list)):
        row = []
        TR = TR_list[i]

        # Filter VRs matching current TR length
        valid_VRs = [vr for vr in VR_list if len(vr) == len(TR)]

        if not valid_VRs:
            # No compatible VRs
            row = [-np.inf] * len(VR_list)
        else:
            # Compute likelihoods for all compatible VRs
            batch_TRs = [TR] * len(valid_VRs)
            log_likelihoods = compute_likelihood_batch(
                batch_TRs,
                valid_VRs
            )

            idx = 0
            for vr in VR_list:
                if len(vr) != len(TR):
                    row.append(-np.inf)
                else:
                    row.append(log_likelihoods[idx])
                    idx += 1

        result_matrix.append(row)

    return result_matrix
