"""Deep learning models to predict the population of VR (Variable Region) sequences generated by a given TR design. Uses LSTM neural networks trained on DGRec experimental data to model bRT's position-dependent, context-dependent error-prone reverse transcription, including the snowball effect where prior mutations increase subsequent error rates.

Docs: https://dbikard.github.io/dgrec/API/lstm.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/API/09_lstm.ipynb.

# %% auto #0
__all__ = ['EPS', 'one_hot_encode', 'one_hot_decode', 'separate_model', 'generate_sequence_from_onehot', 'sequences_same_length',
           'pad_sequence', 'to_tensor_inputs', 'generate_sequences', 'generate_sequences_oneTR',
           'predict_protein_diversity', 'compute_likelihood', 'compute_likelihood_batch', 'compute_likelihood_list',
           'compute_likelihood_matrix']

# %% ../nbs/API/09_lstm.ipynb #f6f95cf2-5340-4818-8b9e-246fea3f7879
import logomaker
import numpy as np
from tqdm import tqdm
from .example_data import get_example_data_dir
import os
import matplotlib.pyplot as plt
from collections import Counter,defaultdict
from itertools import product
from .utils import (codon_usage_ecoli, genetic_code, CODON_TO_AA,
                          AA, AA_IDS, AA_TO_CODONS, nt_to_codons,
                          codons_to_aa, nt_prot)

try:
    import tensorflow as tf
    from tensorflow.keras.utils import to_categorical
    from tensorflow.keras import layers, models
    from tensorflow.keras.models import load_model
    import tensorflow.keras.backend as K
    from tensorflow.keras.utils import register_keras_serializable
    _TF_AVAILABLE = True
except ImportError:
    _TF_AVAILABLE = False

EPS = 1e-8

# %% ../nbs/API/09_lstm.ipynb #zwq1hs8fd0r
def _require_tensorflow():
    """Raise an informative error if TensorFlow is not installed."""
    if not _TF_AVAILABLE:
        raise ImportError(
            "TensorFlow is required for LSTM-based sequence generation. "
            "Install it with: pip install dgrec[lstm]"
        )

# %% ../nbs/API/09_lstm.ipynb #0af10dfc-65cc-4e39-a9a7-56a9b72ad7fa
if _TF_AVAILABLE:
    # --- Custom loss and metrics ---
    @tf.keras.utils.register_keras_serializable(package="custom_losses")
    def masked_categorical_crossentropy(y_true, y_pred, mask=None):
        per_timestep_loss = tf.keras.losses.categorical_crossentropy(y_true, y_pred)
        if mask is not None:
            if len(mask.shape) == 3:
                mask = tf.reduce_max(mask, axis=-1)
            per_timestep_loss *= mask
            loss = tf.reduce_sum(per_timestep_loss) / (tf.reduce_sum(mask) + EPS)
        else:
            mask = tf.cast(tf.reduce_max(tf.abs(y_true), axis=-1) > 0, tf.float32)
            per_timestep_loss *= mask
            loss = tf.reduce_sum(per_timestep_loss) / (tf.reduce_sum(mask) + EPS)
        return loss
    
    @tf.keras.utils.register_keras_serializable(package="custom_metrics")
    def masked_accuracy(y_true, y_pred, mask=None):
        mask_internal = tf.cast(tf.reduce_max(tf.abs(y_true), axis=-1) > 0, tf.float32) if mask is None else tf.cast(mask, tf.float32)
        if len(mask_internal.shape) == 3:
            mask_internal = tf.reduce_max(mask_internal, axis=-1)
        y_true_labels = tf.argmax(y_true, axis=-1)
        y_pred_labels = tf.argmax(y_pred, axis=-1)
        matches = tf.cast(tf.equal(y_true_labels, y_pred_labels), tf.float32) * mask_internal
        return tf.reduce_sum(matches) / (tf.reduce_sum(mask_internal) + EPS)
    
    @tf.keras.utils.register_keras_serializable()
    class DetachMask(layers.Layer):
        def call(self, inputs):
            return tf.identity(inputs)
        def compute_mask(self, inputs, mask=None):
            return None
else:
    def masked_categorical_crossentropy(y_true, y_pred):
        _require_tensorflow()

    def masked_accuracy(y_true, y_pred):
        _require_tensorflow()
    def DetachMask(layer):
        _require_tensorflow()

def one_hot_encode(sequence, vocab_size=4):
    """Converts a DNA sequence string to a one-hot encoded numpy array of shape (len, vocab_size)."""
    _require_tensorflow()
    mapping = {'A': 0, 'C': 1, 'G': 2, 'T': 3}
    integer_encoded = [mapping[base] for base in sequence]
    onehot_encoded = to_categorical(integer_encoded, num_classes=vocab_size)
    return onehot_encoded

def one_hot_decode(encoded_sequence):
    """Converts a one-hot encoded array back to a DNA sequence string."""
    # Reverse the mapping used in encoding
    reverse_mapping = {0: 'A', 1: 'C', 2: 'G', 3: 'T'}
    
    # Get the index of the max value in each one-hot vector (which corresponds to the base index)
    integer_decoded = np.argmax(encoded_sequence, axis=1)
    
    # Convert the integer sequence back to the DNA bases using the reverse mapping
    decoded_sequence = ''.join([reverse_mapping[i] for i in integer_decoded])
    
    return decoded_sequence

def separate_model(model):
    """
    Disentangle the two-stage masked LSTM model into two parts:
      1. First BiLSTM + TimeDistributed Dense layers
      2. Second LSTM + Final Dense (with initial states for generation)
    """
    _require_tensorflow()
    lstm_units = 16
    vocab_size = 4  # A, C, G, T

    # --- Part 1: First BiLSTM + Dense(s) ---
    inputs = layers.Input(shape=(None, vocab_size+1), name="DNA_input_sep")

    masked_seq = layers.Masking(mask_value=0.0)(inputs)
    bilstm_out = layers.Bidirectional(
        layers.LSTM(lstm_units//2, return_sequences=True),
        name="bilstm_1_sep"
    )(masked_seq)

    inter_dense_out = layers.TimeDistributed(
        layers.Dense(vocab_size+2, activation="softmax"),
        name="inter_dense_sep"
    )(bilstm_out)

    inter_dense_relu_out = layers.TimeDistributed(
        layers.Dense(2, activation="relu"),
        name="inter_dense_relu_sep"
    )(bilstm_out)

    # First part outputs both intermediate representations
    first_part_model = models.Model(
        inputs=inputs,
        outputs=[inter_dense_out, inter_dense_relu_out]
    )

    # Transfer weights by name
    first_part_model.get_layer("bilstm_1_sep").set_weights(
        model.get_layer("bilstm_1").get_weights()
    )
    first_part_model.get_layer("inter_dense_sep").set_weights(
        model.get_layer("intermediate_dense").get_weights()
    )
    first_part_model.get_layer("inter_dense_relu_sep").set_weights(
        model.get_layer("intermediate_dense_relu").get_weights()
    )

    # --- Part 2: Second LSTM + Final Dense ---
    inputs_seq = layers.Input(shape=(None, vocab_size+1), name="DNA_input2_sep")
    inputs_mut = layers.Input(shape=(None, 2 * vocab_size + 1), name="mutation_input2_sep")
    inter_out = layers.Input(shape=(None, vocab_size+2), name="inter_dense_out_sep")
    inter_relu_out = layers.Input(shape=(None, 2), name="inter_dense_relu_out_sep")
    initial_h = layers.Input(shape=(lstm_units,), name="init_h")
    initial_c = layers.Input(shape=(lstm_units,), name="init_c")

    concat_inputs = layers.Concatenate(name="concat_sep")(
        [inputs_seq, inputs_mut, inter_out, inter_relu_out]
    )
    masked_concat = layers.Masking(mask_value=0.0)(concat_inputs)

    lstm_out, state_h, state_c = layers.LSTM(
        lstm_units, return_sequences=True, return_state=True, name="lstm_2_sep"
    )(masked_concat, initial_state=[initial_h, initial_c])

    final_out = layers.TimeDistributed(
        layers.Dense(vocab_size, activation="softmax"),
        name="final_dense_sep"
    )(lstm_out)

    second_part_model = models.Model(
        inputs=[inputs_seq, inputs_mut, inter_out, inter_relu_out, initial_h, initial_c],
        outputs=[final_out, state_h, state_c]
    )

    # Transfer weights
    second_part_model.get_layer("lstm_2_sep").set_weights(
        model.get_layer("lstm_2").get_weights()
    )
    second_part_model.get_layer("final_dense_sep").set_weights(
        model.get_layer("final_dense").get_weights()
    )

    return first_part_model, second_part_model

_models_cache = {}

def _get_models():
    """Load LSTM models on first use."""
    _require_tensorflow()
    if 'firstmodel' not in _models_cache:
        _data_path = get_example_data_dir()
        _model_name = 'LSTM_model_8_16.keras'
        _model_path = os.path.join(_data_path, _model_name)
        # --- Load your full trained model first ---
        model_TR_to_VR = tf.keras.models.load_model(
            _model_path, #"LSTM_model_8_16_tf220.keras"
            custom_objects={
                'masked_categorical_crossentropy': masked_categorical_crossentropy,
                'masked_accuracy': masked_accuracy,
                'DetachMask': DetachMask  # placeholder for custom DetachMask
            }
        )
        _models_cache['firstmodel'], _models_cache['secondmodel'] = separate_model(model_TR_to_VR)
    return _models_cache['firstmodel'], _models_cache['secondmodel']

def generate_sequence_from_onehot(X, firstmodel=None, secondmodel=None):
    """
    Generate a sequence using separated masked LSTM models.
    
    X: one-hot encoded sequence (batch, time, vocab_size+2)  # input_seq
    firstmodel: first part model (BiLSTM -> [softmax dense, ReLU dense])
    secondmodel: second part model (Concat -> LSTM -> final dense)
    """
    if firstmodel is None or secondmodel is None:
        firstmodel, secondmodel = _get_models()
    size, seq_length, input_dim = X.shape
    vocab_size = 4   # A, C, G, T
    lstm_units = 16

    # Initial states for second LSTM
    initial_h = np.zeros((size, lstm_units))
    initial_c = np.zeros((size, lstm_units))

    # First part (BiLSTM + two dense layers)
    inter_softmax_out, inter_relu_out = firstmodel.predict(X)

    # Mutation input (start token)
    X_mut = np.zeros((size, 1, vocab_size * 2 + 1))
    X_mut[:, 0, -1] = 1  # mark start

    generated_sequence = np.zeros((size, seq_length, vocab_size))

    for t in tqdm(range(seq_length), desc="Generating sequence"):
        output, new_h, new_c = secondmodel.predict([
            X[:, t:t+1, :],                       # input_seq at step t
            X_mut,                                # mutation input
            inter_softmax_out[:, t:t+1, :],       # intermediate softmax output
            inter_relu_out[:, t:t+1, :],          # intermediate relu output
            initial_h, initial_c                  # LSTM states
        ],verbose=0)

        # Sample next nucleotide
        probs = output[:, 0, :]  # (batch, vocab_size)
        next_word_idx = [np.random.choice(vocab_size, p=p) for p in probs]
        next_word_one_hot = np.zeros((size, vocab_size))
        next_word_one_hot[np.arange(size), next_word_idx] = 1

        generated_sequence[:, t, :] = next_word_one_hot

        # Update states
        initial_h, initial_c = new_h, new_c

        # Update mutation input for next step
        if t < seq_length - 1:
            X_mut[:, 0, :vocab_size] = X[:, t, :vocab_size]        # original nucleotide
            X_mut[:, 0, vocab_size:2*vocab_size] = next_word_one_hot  # predicted nucleotide
            X_mut[:, 0, -1] = 0  # remove start flag after t=0

    return generated_sequence


def sequences_same_length(sequences):
    """
    Check if all sequences in a list have the same length.
    
    Parameters:
    - sequences: list of sequences (e.g., strings, lists, or arrays)
    
    Returns:
    - bool: True if all sequences have the same length, False otherwise.
    """
    # Get the length of the first sequence
    first_length = len(sequences[0])

    # Check if all sequences have the same length
    for seq in sequences:
        if len(seq) != first_length:
            return False

    return True


def pad_sequence(seq, maxlen, padding_value=0):
    """Right-pads a 2D array to the specified length with padding_value."""
    pad_width = ((0, maxlen - seq.shape[0]), (0, 0))  # pad rows only
    return np.pad(seq, pad_width, mode='constant', constant_values=padding_value)

def to_tensor_inputs(*args):
    """Converts numpy arrays to TensorFlow tensors."""
    _require_tensorflow()
    return [tf.convert_to_tensor(x) for x in args]

# %% ../nbs/API/09_lstm.ipynb #8a80d927-30cc-4946-bfc5-3fb934471726
def generate_sequences(X_seq: list[str] #list of TR sequences
                      ) -> list[str]:
    """
    Generate VR sequences from a list of TR sequences.

    Each TR sequence produces exactly one VR sequence.

    Parameters
    ----------
    X_seq : list of str
        List of TR nucleotide sequences (e.g. "ATCG").
        For faster generation, all sequences should have the same length.

    Returns
    -------
    list of str
        List of generated VR sequences, in the same order as `X_seq`.

    Notes
    -----
    - If all input sequences have the same length, generation is vectorized
      for improved performance.
    - Output sequences are returned in the original (non-reversed) order.
    """
    X = [
        np.concatenate(
            (
                one_hot_encode(seq[::-1]),
                [[i] for i in range(len(seq))]
            ),
            axis=1
        )
        for seq in X_seq
    ]

    if sequences_same_length(X_seq):
        Y = generate_sequence_from_onehot(np.array(X))
        return [one_hot_decode(y)[::-1] for y in Y]

    max_len = max(len(seq) + 2 for seq in X_seq)
    lengths = np.array([len(seq) for seq in X_seq])

    X_padded = np.array([pad_sequence(seq, max_len) for seq in X])
    Y = generate_sequence_from_onehot(X_padded)

    return [
        one_hot_decode(Y[i])[:lengths[i]][::-1]
        for i in range(len(Y))
    ]

#| export
def generate_sequences_oneTR(TR: str #TR sequence
                             , n: int = 1000 #Number of VR to generate
                            ) -> list[str]:
    """
    Generate multiple VR sequences from a single TR sequence.

    Parameters
    ----------
    TR : str
        Input TR nucleotide sequence.
    n : int, default=1000
        Number of VR sequences to generate.

    Returns
    -------
    list of str
        List of `n` generated VR sequences.
    """
    return generate_sequences([TR] * n)

# %% ../nbs/API/09_lstm.ipynb #493ad454-95a7-4eff-bd9c-ae857afa003e
def predict_protein_diversity(
    TR: str #The TR sequence 
    ,NDGR: int = 100 #Number of VR to generate
    ,offset: int = 0 #The offset for protein translation
    ,plot: bool = False #draw the amino-acid sequence logo
) -> Counter:
    """
    Evaluate protein diversity accessible from a TR sequence via DGR.

    Generates VR sequences from a single TR, translates them into proteins,
    and returns the amino-acid frequencies; pass `plot=True` for a sequence logo.

    Parameters
    ----------
    TR : str
        Input TR nucleotide sequence.
    NDGR : int, default=100
        Number of VR sequences to generate from the TR.
    offset : int, default=0
        Nucleotide offset applied before translation to protein.

    Returns
    -------
    collections.Counter
        Counts of translated protein sequences.

    Notes
    -----
    - Translation is performed after applying the nucleotide `offset`.
    - The sequence logo shows per-position amino-acid probabilities.
    """
    VR = generate_sequences_oneTR(TR, NDGR)

    proteins = [
        nt_prot(vr[offset:])
        for vr in VR
    ]

    # Build amino-acid count matrix
    df = logomaker.alignment_to_matrix(
        sequences=proteins,
        to_type="counts"
    )

    # Normalize counts to probabilities per position
    df = df.div(df.sum(axis=1), axis=0)

    if plot:
        plt.figure(figsize=(12, 4))
        logomaker.Logo(
            df,
            color_scheme="chemistry",
            shade_below=0.5,
            fade_below=0.5
        )
        plt.title("Protein Sequence Logo")
        plt.ylabel("Frequency")
        plt.xlabel("Amino acid position")
        plt.tight_layout()
        plt.show()

    return Counter(proteins)


# %% ../nbs/API/09_lstm.ipynb #5ed2963a
def _teacher_forced_loglik(TR_batch, VR_batch):
    """Log-likelihood of each VR given its TR, by teacher forcing.

    The decoder is a single-step model: given one position, the previous
    (TR, VR) pair and the LSTM state, it returns the distribution for that
    position only. Feeding it the whole sequence at once returns just the last
    position, which is what `generate_sequence_from_onehot` works around by
    stepping. The likelihood has to be computed the same way: step through the
    sequence, read off the probability of the base the VR actually carries, and
    carry the state forward.
    """
    assert all(len(tr) == len(vr) for tr, vr in zip(TR_batch, VR_batch)), "Mismatched lengths"
    assert len({len(tr) for tr in TR_batch}) <= 1, "All sequences in a batch must share a length"
    if not TR_batch: return np.array([])

    firstmodel, secondmodel = _get_models()
    vocab_size, lstm_units = 4, 16
    n, seq_length = len(TR_batch), len(TR_batch[0])

    # one-hot of the reversed TR, plus the positional index
    X = np.array([
        np.concatenate((one_hot_encode(tr[::-1]), [[i] for i in range(seq_length)]), axis=1)
        for tr in TR_batch
    ])
    Y = np.array([one_hot_encode(vr[::-1]) for vr in VR_batch])

    inter_softmax_out, inter_relu_out = firstmodel.predict(X, verbose=0)
    h = np.zeros((n, lstm_units))
    c = np.zeros((n, lstm_units))
    X_mut = np.zeros((n, 1, 2 * vocab_size + 1))
    X_mut[:, 0, -1] = 1  # start token

    log_likelihoods = np.zeros(n)
    for t in range(seq_length):
        output, h, c = secondmodel.predict(
            [X[:, t:t+1, :], X_mut,
             inter_softmax_out[:, t:t+1, :], inter_relu_out[:, t:t+1, :], h, c],
            verbose=0)
        probs = output[:, 0, :]
        idx = Y[:, t, :].argmax(axis=1)
        log_likelihoods += np.log(probs[np.arange(n), idx] + 1e-8)
        if t < seq_length - 1:
            X_mut[:, 0, :vocab_size] = X[:, t, :vocab_size]            # the TR base
            X_mut[:, 0, vocab_size:2*vocab_size] = Y[:, t, :]          # the VR base actually seen
            X_mut[:, 0, -1] = 0
    return log_likelihoods

# %% ../nbs/API/09_lstm.ipynb #265d2712-2bfa-482d-8c19-420b904a0350
def compute_likelihood(TR, VR):
    """
    Compute the log-likelihood of generating a variant sequence (VR)
    given a template/reference sequence (TR).

    Parameters
    ----------
    TR : str
        Reference/template sequence.
    VR : str
        Variant sequence to score.

    Returns
    -------
    float
        Log-likelihood of VR given TR.
    """
    assert len(TR) == len(VR), "Mismatched lengths"
    return float(_teacher_forced_loglik([TR], [VR])[0])

# %% ../nbs/API/09_lstm.ipynb #4f2e37b5-bee4-4b0a-b053-c032307a047e
def compute_likelihood_batch(TR_batch, VR_batch):
    """
    Compute log-likelihoods for a batch of (TR, VR) sequence pairs.

    All sequences in the batch must:
    - Have matching TR/VR lengths
    - Share the same sequence length across the batch

    Parameters
    ----------
    TR_batch : list of str
        List of reference/template sequences.
    VR_batch : list of str
        List of variant sequences.

    Returns
    -------
    list of float
        Log-likelihoods for each (TR, VR) pair.
    """
    return [float(x) for x in _teacher_forced_loglik(list(TR_batch), list(VR_batch))]

# %% ../nbs/API/09_lstm.ipynb #c2bc5a52-813b-4d64-8c3b-21b5d5e01ce9
def compute_likelihood_list(TR_list, VR_list):
    """
    Compute log-likelihoods for (TR, VR) pairs, of any mix of lengths.

    Parameters
    ----------
    TR_list : list of str
        Reference/template sequences.
    VR_list : list of str
        Variant sequences.

    Returns
    -------
    list of float
        Log-likelihoods in the same order as input.
    """
    assert len(TR_list) == len(VR_list)
    assert all(len(tr) == len(vr) for tr, vr in zip(TR_list, VR_list)), \
        "Mismatched TR/VR lengths"

    by_length = {}
    for i, tr in enumerate(TR_list): by_length.setdefault(len(tr), []).append(i)

    out = [None] * len(TR_list)
    for _, idxs in by_length.items():
        lls = _teacher_forced_loglik([TR_list[i] for i in idxs], [VR_list[i] for i in idxs])
        for i, ll in zip(idxs, lls): out[i] = float(ll)
    return out

# %% ../nbs/API/09_lstm.ipynb #48e675a6-4402-43cf-88b3-a78bee57ac3f
def compute_likelihood_matrix(TR_list, VR_list, batch_size=64):
    """
    Compute a matrix of log-likelihoods where each entry (i, j)
    corresponds to the log-likelihood of generating VR_list[j]
    from TR_list[i].

    Sequences with mismatched lengths are assigned -inf.

    Parameters
    ----------
    TR_list : list of str
        List of reference/template sequences.
    VR_list : list of str
        List of variant sequences.
    batch_size : int
        Unused; kept for backwards compatibility.

    Returns
    -------
    list of list of float
        Matrix of log-likelihoods, rows indexed by TR and columns by VR.
    """
    matrix = [[float("-inf")] * len(VR_list) for _ in TR_list]
    for i, tr in enumerate(TR_list):
        cols = [j for j, vr in enumerate(VR_list) if len(vr) == len(tr)]
        if not cols: continue
        lls = _teacher_forced_loglik([tr] * len(cols), [VR_list[j] for j in cols])
        for j, ll in zip(cols, lls): matrix[i][j] = float(ll)
    return matrix
